### ISSUE TITLE
一个因handler作用域bug造成的渲染异常

### ISSUE THREAD

**Issue by malash** [ssnau/noflux#1]
# 复现

```jsx
import React, { Component } from 'react';
import HomePage from './home';
import { connect, state } from 'noflux';


state.load({
  value: 'init',
});

// 打印所有listener
setInterval(() => {
  console.log('count', state.listeners('change'));
}, 1000)

@connect()
class Child extends Component {
  render() {
    return (
      <div>
        <h1>Child {this.props.children}</h1>
        <p>
          {state.get('value')}
        </p>
      </div>
    )
  }
}

// 祖先组件不可以被@connect
// @connect()
export default class App extends Component {

  state = { disabled: false };

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    setTimeout(() => {
      console.log('disable 2');
      this.setState({ disabled: true });
    }, 2000);
    setTimeout(() => {
      console.log('change value')
      state.set('value', 'new');
    }, 4000);
  }

  render() {
    console.log('App render');
    return (
      <div>
        <Child>1</Child>
        {!this.state.disabled &&
          <Child>2</Child>
        }
        <Child>3</Child>
      </div>
    );
  }
}
```

# 说明

组件类：继承于`React.Component`的`class`

组件实例：`React.createElement`产生的实例，即`<Component></Component>`

# 条件

复现该问题条件略苛刻：

0. 组件类必须被`@connect`
1. 必须产生该组件类的多个实例
2. 必须卸载其中的一个组件实例，且不能是最后一个
3. 卸载后需要通过`noflux`触发更新
4. 这些组件的祖先组件都不可以被`@connect`过

DOM树结构如下：

```
App
 - @connect Child
 - @connect Child(will be delete)
 - @connect Child
```

# 现象

这段代码将在屏幕上渲染三个`Child`组件：

![image](https://cloud.githubusercontent.com/assets/1812118/24810219/2b3308a0-1bf4-11e7-9f9c-b99f1d41cadb.png)

2s后通过`&&`卸载掉第二个：

![image](https://cloud.githubusercontent.com/assets/1812118/24810239/409dadbc-1bf4-11e7-8112-f90373555064.png)

再过2s，通过state.set('value', 'new')触发剩余的两个`Child`组件重新渲染。但事实上最后一个组件会渲染失败：

![image](https://cloud.githubusercontent.com/assets/1812118/24810278/703c00fa-1bf4-11e7-93a8-619215c84173.png)

# 原因

问题出在这一行： https://github.com/ssnau/noflux/blob/master/lib/connect.js#L25

对`state`的监听是在组件实例作用域内的，每个组件实例会监听一次；但`handler`的保存却是在`@connect`作用域的，每个组件类保持一个`handler`。两者数量并不匹配，事实上`handler`保存的是最后一个实例的监听器。

当出现组件实例卸载的情况（如通过`&&`控制），`componentWillUnmount`中会调用`removeListener`解除监听，就把最后那个组件实例的监听解除了。因此复现时最后一个组件内的值不会被更新。

# 解决方法

作用域问题，两种解决思路：

1. 将`handler`保存在组件实例的`this`中

2. 将`handler`利用闭包进行保持在组件实例中

**Comment by ssnau** [comment]
👍
